set(COMMON_prefix ${PROJECT_SOURCE_DIR}/common)
set(COMMON_INCLUDE_DIRS ${COMMON_prefix}/include)
set(COMMON_SRC_DIRS ${COMMON_prefix}/src)
aux_source_directory(${COMMON_SRC_DIRS} SRC)
set(${COMMON_SRC_FILES} ${SRC})
set(COMMON_RESOURCES_DIRS ${COMMON_prefix}/resources)