set(COMMON_prefix ${PROJECT_SOURCE_DIR}/common)
set(COMMON_INCLUDE_DIRS ${COMMON_prefix}/include)
set(COMMON_SRC_DIRS ${COMMON_prefix}/src)
aux_source_directory(${COMMON_SRC_DIRS} COMMON_SRC)
aux_source_directory(${COMMON_SRC_DIRS}/engin COMMON_SRC_ENGIN)
list(APPEND COMMON_SRC ${COMMON_SRC_ENGIN})
set(COMMON_RESOURCES_DIRS ${COMMON_prefix}/resources)
set(COMMON_LIBRARY_NAME "common")
set(COMMON_LIBRARIES "-L${PROJECT_SOURCE_DIR}/common/lib -l${COMMON_LIBRARY_NAME}")